module Upfluence
  module Resources
    COUNTRIES = %w[
      US FR GB DE CH AF AL DZ AS AD AO AI
      AG AR AM AW AU AT AZ BS BH BD BB BY
      BE BZ BJ BM BT BO BA BW BR BN BG BF
      BI CV KH CM CA KY CF TD CL CN CO KM
      CG CD CK CI HR CU CY CZ DK DJ DM DO
      GW GY HT VA HN HK HU IS IN ID IR IQ
      IE IM IL IT JM JP JE JO KZ KE KI KP
      KR KW KG LA LV LB LI LS LR LY LT LU
      MO MK MG MW MY MV ML MT MH MQ MR MU
      MX FM MD MC MN ME MS MA MZ MM NA NR
      NP NL NC NZ NI NE NG NO OM PK PW PS
      PA PG PY PE PH PL PT PR QA RE RO RU
      RW KN LC VC WS SM ST SA SN RS SC SL
      SG SK SI SB SO ZA ES LK SD SR SZ SE
      SY TW TJ TZ TH TL TG TO TT TN TR TM
      TC TV UG UA AE GB UY UZ VU VE VN VG
      VI EH YE ZM ZW CR
    ].freeze
  end
end
